### PR TITLE
Refactored the project structure and added carthage support

### PR DESCRIPTION
**Pull request by patricks**

### CODE REVIEW

**Comment by GabrielAlva** [comment]
Hi Patrick, 
Thank you very much for contributing, is there anything else I need to do to set up the Carthage support?

**Comment by patricks** [comment]
No, I have already imported Swift-Prompts via Carthage into my project.

**Comment by patricks** [comment]
You should update the Readme file. I have set the wrong repo (mine) there. Sorry.

**Comment by GabrielAlva** [comment]
Do you happen to know how to add the Carthage badge to the other ones on the project?

**Pull request merged**
